// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class CarResponsible
{
    public int Id { get; set; }

    public int CarId { get; set; }

    public int EmpId { get; set; }

    public virtual CarManagement Car { get; set; }

    public virtual Employee Emp { get; set; }
}