// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class CartRoomItem
{
    public int Id { get; set; }

    public string Phone { get; set; }

    public string Uid { get; set; }

    public bool Selected { get; set; }

    public int TypeId { get; set; }

    public int RoomId { get; set; }

    public DateTime CheckInDate { get; set; }

    public DateTime CheckOutDate { get; set; }

    public string Remark { get; set; }

    public virtual RoomType Type { get; set; }
}