// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class CarTaxiOrderItem
{
    public int Id { get; set; }

    public int CarId { get; set; }

    public string PickUpLongtitude { get; set; }

    public string PickUpLatitude { get; set; }

    public string PickUpLocation { get; set; }

    public string DestinationLatitude { get; set; }

    public string DestinationLongtitude { get; set; }

    public string DestinationLocation { get; set; }

    public decimal Total { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public int EmpId { get; set; }

    public int MemberId { get; set; }

    public virtual Car Car { get; set; }

    public virtual Employee Emp { get; set; }

    public virtual Member Member { get; set; }
}