// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class Cipher
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string CipherString { get; set; }

    public string CipherKey { get; set; }
}