// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class CouponRoomCountSameDate
{
    public int Id { get; set; }

    public int CouponId { get; set; }

    public int RoomTypeId { get; set; }

    public int Count { get; set; }

    public int PercentOff { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual RoomType RoomType { get; set; }
}