// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class Coupon
{
    public int Id { get; set; }

    public int TypeId { get; set; }

    public DateTime AllowStart { get; set; }

    public DateTime AllowEnd { get; set; }

    public bool Cumulative { get; set; }

    public string Comment { get; set; }

    public virtual ICollection<CouponMember> CouponMembers { get; set; } = new List<CouponMember>();

    public virtual CouponRoomCountSameDate CouponRoomCountSameDate { get; set; }

    public virtual CouponRoomTimeSpan CouponRoomTimeSpan { get; set; }

    public virtual CouponThresholdDiscount CouponThresholdDiscount { get; set; }

    public virtual CouponType Type { get; set; }
}