// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class CouponThresholdDiscount
{
    public int Id { get; set; }

    public int CouponId { get; set; }

    public int Threshold { get; set; }

    public int Discount { get; set; }

    public virtual Coupon Coupon { get; set; }
}