// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Salt { get; set; }

    public DateTime HireDate { get; set; }

    public DateTime? LeaveDate { get; set; }

    public string BloodType { get; set; }

    public string IdentityNumber { get; set; }

    public DateTime Birthday { get; set; }

    public bool Gender { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public virtual ICollection<CarMaintenance> CarMaintenances { get; set; } = new List<CarMaintenance>();

    public virtual ICollection<CarRentCartItem> CarRentCartItems { get; set; } = new List<CarRentCartItem>();

    public virtual ICollection<CarRentOrderItem> CarRentOrderItems { get; set; } = new List<CarRentOrderItem>();

    public virtual ICollection<CarResponsible> CarResponsibles { get; set; } = new List<CarResponsible>();

    public virtual ICollection<CarTaxiCartItem> CarTaxiCartItems { get; set; } = new List<CarTaxiCartItem>();

    public virtual ICollection<CarTaxiOrderItem> CarTaxiOrderItems { get; set; } = new List<CarTaxiOrderItem>();

    public virtual ICollection<EmployeeRole> EmployeeRoles { get; set; } = new List<EmployeeRole>();
}