// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class HallMenu
{
    public int Id { get; set; }

    public string DishName { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public int CategoryId { get; set; }

    public string PhotoPath { get; set; }

    public string Keywords { get; set; }

    public virtual HallDishCategory Category { get; set; }

    public virtual ICollection<HallMenuSchedule> HallMenuSchedules { get; set; } = new List<HallMenuSchedule>();
}