// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class HallOrderVw
{
    public int Id { get; set; }

    public int HallId { get; set; }

    public int? UserId { get; set; }

    public int? Guests { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public bool BookingStatus { get; set; }

    public string Name { get; set; }

    public string CellPhone { get; set; }

    public string Email { get; set; }

    public string FilePath { get; set; }

    public int? TotalQty { get; set; }

    public int? TotalPrice { get; set; }

    public string ProductName { get; set; }

    public int ProductId { get; set; }

    public int Price { get; set; }

    public int Qty { get; set; }

    public int? SubTotal { get; set; }
}