// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class Reservation
{
    public int Id { get; set; }

    public int? ClientId { get; set; }

    public int ReservationStatusId { get; set; }

    public DateTime CreateTime { get; set; }

    public string ClientName { get; set; }

    public string PhoneNumber { get; set; }

    public virtual ICollection<ReservationItem> ReservationItems { get; set; } = new List<ReservationItem>();

    public virtual ReservationStatus ReservationStatus { get; set; }
}