// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class ReservationItem
{
    public int Id { get; set; }

    public int ReservationId { get; set; }

    public int ServiceDetailId { get; set; }

    public DateTime AppointmentDate { get; set; }

    public int AppointmentTimePeriodId { get; set; }

    public int TotalDuration { get; set; }

    public int? RoomId { get; set; }

    public int? RoomStatusId { get; set; }

    public int Subtotal { get; set; }

    public virtual ReservationAppointmentTimePeriod AppointmentTimePeriod { get; set; }

    public virtual Reservation Reservation { get; set; }

    public virtual ReservationRoom Room { get; set; }

    public virtual ReservationRoomStatus RoomStatus { get; set; }

    public virtual ReservationServiceDetail ServiceDetail { get; set; }
}