// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class ReservationRoom
{
    public int Id { get; set; }

    public string RoomName { get; set; }

    public int RoomTypeId { get; set; }

    public int Capacity { get; set; }

    public virtual ICollection<ReservationItem> ReservationItems { get; set; } = new List<ReservationItem>();

    public virtual ReservationRoomType RoomType { get; set; }
}