// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class ReservationServiceDetail
{
    public int Id { get; set; }

    public int ServicesTypeId { get; set; }

    public string ServiceDetailName { get; set; }

    public int Time { get; set; }

    public int Price { get; set; }

    public string Description { get; set; }

    public string ImgUrl { get; set; }

    public virtual ICollection<ReservationItem> ReservationItems { get; set; } = new List<ReservationItem>();

    public virtual ReservationServicesType ServicesType { get; set; }
}