// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class ReservationStatus
{
    public int Id { get; set; }

    public string StatusName { get; set; }

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();
}