// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class ReservationTotalPriceView
{
    public int Id { get; set; }

    public int? ClientId { get; set; }

    public int ReservationStatusId { get; set; }

    public DateTime CreateTime { get; set; }

    public int? TotalSubtotal { get; set; }
}