// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class ReservationAppointmentTimePeriod
{
    public int Id { get; set; }

    public string TimePeriod { get; set; }

    public string Description { get; set; }

    public int TimeValue { get; set; }

    public virtual ICollection<ReservationItem> ReservationItems { get; set; } = new List<ReservationItem>();
}