// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class RestaurantPeriod
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int UnitPrice { get; set; }

    public virtual ICollection<RestaurantReservation> RestaurantReservations { get; set; } = new List<RestaurantReservation>();
}