// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class RestaurantReservation
{
    public int Id { get; set; }

    public int CustomerId { get; set; }

    public DateTime Date { get; set; }

    public int Counts { get; set; }

    public int PeriodId { get; set; }

    public int? StatusId { get; set; }

    public int SeatId { get; set; }

    public virtual RestaurantCustomer Customer { get; set; }

    public virtual RestaurantPeriod Period { get; set; }

    public virtual RestaurantSeat Seat { get; set; }

    public virtual RestaurantStatus Status { get; set; }
}