// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class RoleAuthorization
{
    public int Id { get; set; }

    public int RoleId { get; set; }

    public int AuthorizationId { get; set; }

    public virtual Authorization Authorization { get; set; }

    public virtual Role Role { get; set; }
}