// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class Role
{
    public int Id { get; set; }

    public string RoleName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<EmployeeRole> EmployeeRoles { get; set; } = new List<EmployeeRole>();

    public virtual ICollection<RoleAuthorization> RoleAuthorizations { get; set; } = new List<RoleAuthorization>();
}