// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class RoomDetailImg
{
    public int RoomTypeId { get; set; }

    public string ImgUrl { get; set; }

    public int ImgSeq { get; set; }
}