// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class RoomType
{
    public int RoomTypeId { get; set; }

    public string TypeName { get; set; }

    public string Description { get; set; }

    public int Capacity { get; set; }

    public string BedType { get; set; }

    public int RoomCount { get; set; }

    public int WeekdayPrice { get; set; }

    public int WeekendPrice { get; set; }

    public int HolidayPrice { get; set; }

    public string ImageUrl { get; set; }

    public int? Size { get; set; }

    public virtual ICollection<CartRoomItem> CartRoomItems { get; set; } = new List<CartRoomItem>();

    public virtual ICollection<CouponRoomCountSameDate> CouponRoomCountSameDates { get; set; } = new List<CouponRoomCountSameDate>();

    public virtual ICollection<CouponRoomTimeSpan> CouponRoomTimeSpans { get; set; } = new List<CouponRoomTimeSpan>();

    public virtual ICollection<Room> Rooms { get; set; } = new List<Room>();
}