// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class RoomDaysPrice
{
    public DateTime Date { get; set; }

    public string Week { get; set; }

    public string IsHoliday { get; set; }

    public string Description { get; set; }

    public int RoomTypeId { get; set; }

    public string TypeName { get; set; }

    public int Price { get; set; }
}