// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class SendedNotification
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int NotificationId { get; set; }

    public bool IsSended { get; set; }

    public virtual Member Member { get; set; }

    public virtual Notification Notification { get; set; }
}