// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class Set
{
    public string Key { get; set; }

    public double Score { get; set; }

    public string Value { get; set; }

    public DateTime? ExpireAt { get; set; }
}