// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class ShoppingCartOrder
{
    public string Id { get; set; }

    public string OrderId { get; set; }

    public string MemberId { get; set; }

    public int Price { get; set; }

    public bool States { get; set; }

    public string Note { get; set; }
}