// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class ShoppingCartDiscountsPriceEqual
{
    public int Id { get; set; }

    public string MainProductId { get; set; }

    public string MatchProductId { get; set; }

    public int Price { get; set; }
}