// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class ShoppingCartDiscountsPriceReduce
{
    public int Id { get; set; }

    public int Price { get; set; }

    public int Discount { get; set; }
}