// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelFuen31.APIs.Models;

public partial class ShoppingCartDiscount
{
    public int Id { get; set; }

    public string FormName { get; set; }

    public string ActivityName { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public string Note { get; set; }
}