// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace HotelFuen31.APIs.Models
{
    public partial class usp_計算訂房價格Result
    {
    }
}
